        #save posterior hyperparameters
        post_hyp_param[i,0] = kernels[0].variance
        post_hyp_param[i,1:4] = kernels[0].lengthscale
        post_hyp_param[i,4] = kernels[1].mul.scale_kernel_fidelity2.variance
        post_hyp_param[i,5:8] = kernels[1].mul.scale_kernel_fidelity2.lengthscale
        post_hyp_param[i,8] = kernels[1].mul.previous_fidelity_fidelity2.variance
        post_hyp_param[i,9] = kernels[1].mul.previous_fidelity_fidelity2.lengthscale
        post_hyp_param[i,10] = kernels[1].bias_kernel_fidelity2.variance
        post_hyp_param[i,11:14] = kernels[1].bias_kernel_fidelity2.lengthscale